config/routes.rb
Nflpool::Application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations'}

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :games do
    resources :picks, only: [:new, :create]
  end

  resources :users, only: :index do
   resources :picks, only: [:index]
  get "leaderboard"
  end

  resources :picks, only: [:edit, :update]

  root to: 'games#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable

  default_scope order('points DESC')

  has_many :picks, dependent: :destroy, order: 'game_id asc'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def picks_count
    self.picks.count
  end

  def user_points
    point_tracker = 0
    self.picks.each do |pick|
      if pick.wager != nil
        if pick.result
          point_tracker = point_tracker + pick.wager
        elsif pick.result == false
          point_tracker = point_tracker - pick.wager
        end
      end
    end
    self.points = point_tracker
    self.save
    point_tracker
  end

def weekly_wagers
  wager_tracker = 0
  self.picks.each do |pick|
    if pick.wager != nil && (pick.game.date.beginning_of_week == Date.current.beginning_of_week)
        wager_tracker = wager_tracker + pick.wager
    end
  end
  if wager_tracker == nil
    0
  else
    wager_tracker
  end
end

def weekly_points
  points_tracker = 0
  self.picks.each do |pick|
    if pick.wager != nil && (pick.game.date.beginning_of_week == Date.current.beginning_of_week)
      if pick.result
        points_tracker = points_tracker + pick.wager
      elsif pick.result == false
        points_tracker = points_tracker - pick.wager
      end
    end
  end
  if points_tracker == nil
    0
  else
    points_tracker
  end
end

def last_week_wagers
  wager_tracker = 0
  self.picks.each do |pick|
    if pick.wager != nil && (pick.game.date.beginning_of_week == 1.week.ago.beginning_of_week.to_date)
        wager_tracker = wager_tracker + pick.wager
    end
  end
  if wager_tracker == nil
    0
  else
    wager_tracker
  end
end

def last_week_points
  points_tracker = 0
  self.picks.each do |pick|
    if pick.wager != nil && (pick.game.date.beginning_of_week == 1.week.ago.beginning_of_week.to_date)
      if pick.result
        points_tracker = points_tracker + pick.wager
      elsif pick.result == false
        points_tracker = points_tracker - pick.wager
      end
    end
  end
  if points_tracker == nil
    0
  else
    points_tracker
  end
end



def full_name
  first_name + " " + last_name
end

def sort_users
  all_users = User.all

end



  # attr_accessible :title, :body
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_admin!, except: [:leaderboard, :picks]

  def index
    @users = User.scoped
  end
end

app/views/users/index.html.erb
<h1>All Users</h1>
<hr>
<table class="table-bordered table-striped table-hover">
  <tr>
    <th>Name</th>
    <th>Picks</th>
  </tr>

<% for user in @users %>
  <tr>
    <td><%= user.profile_name %></td>
    <td><%= link_to 'Picks', user_picks_path(user) %></td>
  </tr>
<% end %>

</table>
<%= link_to 'Back', :back, class: "btn btn-primary" %>

app/views/users/leaderboard.html.erb
<h1>Points Leaderboard</h1>
<hr>
<table class="table-bordered table-striped table-hover" id="leaderboard-spacing">
  <tr>
    <th>Rank</th>
    <th>Name</th>
    <th>Total Points</th>
    <th>Weekly Points Wagered</th>
    <th>Weekly Points Earned</th>
    <th>Previous Points Wagered</th>
    <th>Previous Points Earned</th>
  </tr>

<% @users = User.find_all_by_admin(false) %>
<% user_rank = 1 %>
<% for user in @users %>
    <tr>
      <td><%= user_rank%></td>
      <% user_rank = user_rank + 1%>
      <td><%= link_to user.profile_name, user_picks_path(user) %></td>
      <td><%= user.user_points %></td>
      <td><%= user.weekly_wagers %></td>
      <td><%= user.weekly_points %></td>
      <td><%= user.last_week_wagers %></td>
      <td><%= user.last_week_points %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to "Back To This Week's Games", games_path, class: "btn btn-primary" %>