config/routes.rb
Nflpool::Application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations'}

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :games do
    resources :picks, only: [:new, :create]
  end

  resources :users, only: :index do
   resources :picks, only: [:index]
  get "leaderboard"
  end

  resources :picks, only: [:edit, :update]

  root to: 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :team_one, class_name: "Team", foreign_key: "team_one_id"
	belongs_to :team_two, class_name: "Team", foreign_key: "team_two_id"
	belongs_to :winning_team, class_name: "Team", foreign_key: "winning_team_id"
	has_many :picks, dependent: :destroy
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!, except: :sign_in
  before_filter :ensure_admin!, except: :index
  # GET /games
  # GET /games.json


  def index
    if current_user.admin?
      @games = Game.order("date DESC").page(params[:page]).per(20)
    else
      @games = Game.order("date DESC")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(games_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(games_params)
        format.html { redirect_to games_path, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private

    def games_params
      params.require(:game).permit(:team_one_id, :team_two_id, :winning_team_id, :date, :spread, :bonus)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for(@game, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.input :team_two_id, label: 'Away Team', :include_blank => false,collection: Team.order("name ASC"), label_method: :name %>
  <%= f.input :team_one_id, label: 'Home Team', :include_blank => false,collection: Team.order("name ASC"), label_method: :name %>
  <%= f.input :winning_team_id, label: 'Winner', collection: Team.order("name ASC"), label_method: :name %>
  <%= f.input :spread %>
  <%= f.input :bonus, label: 'Thanksgiving Game', as: :boolean %>
  <%= f.input :date %>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>

<% end %>

app/views/games/_game_tr.html.erb
<tr>
  <td><%= game.date.to_formatted_s(:long) %></td>

  <% if game.picks.find_by(user_id: current_user.id) != nil %>
    <% if game.picks.find_by(user_id: current_user.id).pick_team_id == game.team_two_id %>
      <td><strong><%= game.team_two.name %></strong></td>
      <td><%= game.team_one.name %></td>

    <% else %>
      <td><%= game.team_two.name %></td>
      <td><strong><%= game.team_one.name %></strong></td>
    <% end %>

  <% else %>
    <td><%= game.team_two.name %></td>
    <td><%= game.team_one.name %></td>
  <% end %>

  <td><%= game.spread %></td>
  <td>
    <% pick = game.picks.find_by(user_id: current_user.id) %>
    <% if pick %>
      <%= link_to pick.wager, edit_pick_path(pick) %>
    <% else %>
      <%= link_to 'Pick', new_game_pick_path(game) %>
    <% end %>
  </td>

  <% if current_user.admin? %>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% else %>
  <% end %>
</tr>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<% if current_user.admin? %>
  <h1>All Games</h1>
<% else %>
  <h1>This Week's Games</h1>
<% end %>
<hr>
<div class="table-spacing">
  <table class="table-bordered table-striped table-hover">
    <tr>
      <th>Date</th>
      <th>Away Team</th>
      <th>Home Team</th>
      <th>Spread</th>
      <th>Wager</th>

    </tr>

    <% if current_user.admin? %>
      <% @games.each do |game| %>
        <%= render 'game_tr', game: game %>
      <% end %>
      <%= paginate @games %>
    <% else %>
      <h4>Thursday's games</h4>
      <% @games.each do |game| %>
        <% if game.date.beginning_of_week == Date.current.beginning_of_week %>
          <% if game.date.to_time.wday == 4 %>
            <%= render 'game_tr', game: game %>
          <% end %>
        <% end %>
      <% end %>
    </table>

    <table class="table-bordered table-striped table-hover">
      <tr>
        <th>Date</th>
        <th>Away Team</th>
        <th>Home Team</th>
        <th>Spread</th>
        <th>Wager</th>
      </tr>

      <h4>Sunday's games</h4>
      <% @games.each do |game| %>
        <% if game.date.beginning_of_week == Date.current.beginning_of_week %>
          <% if game.date.to_time.wday == 0 %>
            <%= render 'game_tr', game: game %>
          <% end %>
        <% end %>
      <% end %>
    </table>

    <table class="table-bordered table-striped table-hover">
      <tr>
        <th>Date</th>
        <th>Away Team</th>
        <th>Home Team</th>
        <th>Spread</th>
        <th>Wager</th>
      </tr>

      <h4>Monday's games</h4>
      <% @games.each do |game| %>
        <% if game.date.beginning_of_week == Date.current.beginning_of_week %>
          <% if game.date.to_time.wday == 1 %>
            <%= render 'game_tr', game: game %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </table>
</div>

<br />

<% if current_user.admin? %>
  <%= link_to 'New Game', new_game_path, class: "btn btn-success" %>
<% else %>
<% end %>

app/views/games/new.html.erb
<h1>Add New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p>
  <b>Date:</b>
  <%= @game.date.to_formatted_s(:long) %>
</p>

<p>
  <b>Home Team:</b>
  <%= @game.team_one.name %>
</p>

<p>
  <b>Away Team:</b>
  <%= @game.team_two.name %>
</p>
<% if @game.winning_team_id == nil %>
<% else %>
<p>
  <b>Winning Team:</b>
  <%= @game.winning_team.name %>
</p>
<% end %>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>