config/routes.rb
Nflpool::Application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations'}

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :games do
    resources :picks, only: [:new, :create]
  end

  resources :users, only: :index do
   resources :picks, only: [:index]
  get "leaderboard"
  end

  resources :picks, only: [:edit, :update]

  root to: 'games#index'

end

app/models/pick.rb
class Pick < ActiveRecord::Base
  validates :pick_team_id, presence: { message: 'Please select a team.' }

  belongs_to :pick_team, class_name: "Team", foreign_key: "pick_team_id"
  belongs_to :user
  belongs_to :game

  def result
    if self.game.winning_team_id == nil
      nil
    else
    self.pick_team_id == self.game.winning_team_id
    end
  end

end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_admin!, except: [:index, :new, :edit, :create, :update]
  before_action :authorize_edit, only: [:edit, :update]


  # GET /picks
  # GET /picks.json
  def index
    @user = User.find(params[:user_id])
    @picks = @user.picks.order("created_at DESC").page(params[:page]).per(20)
  end

  # GET /picks/1
  # GET /picks/1.json
  def show
    @pick = @game.picks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pick }
    end
  end

  # GET /picks/new
  # GET /picks/new.json
  def new
    @game = Game.find params[:game_id]
    @pick = @game.picks.find_or_initialize_by(user_id: current_user.id)
  end

  # GET /picks/1/edit
  def edit
    @game = @pick.game
  end

  # POST /picks
  # POST /picks.json
  def create
    @game = Game.find params[:game_id]
    if @game.picks.find_by(user_id: current_user.id)
    else
      @pick = @game.picks.build(picks_params)
      @pick.user = current_user
      @pick.save
    end

    respond_to do |format|
      if @pick.save
        format.html { redirect_to games_path, notice: 'Pick was successfully created.' }
        format.json { render json: @pick, status: :created, location: @pick }
      else
        format.html { render action: "new", id: @pick.id }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /picks/1
  # PUT /picks/1.json
  def update
    respond_to do |format|
      if @pick.update_attributes(picks_params)
        format.html { redirect_to games_path, notice: 'Pick was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picks/1
  # DELETE /picks/1.json
  def destroy
    @pick = Pick.find(params[:id])
    @pick.destroy

    respond_to do |format|
      format.html { redirect_to picks_url }
      format.json { head :no_content }
    end
  end

  private

    def picks_params
      params.require(:pick).permit(:game_id, :pick_team_id, :user_id, :date, :wager) if params[:pick]
    end

    def authorize_edit
      pick_var = Pick.find params[:id]
      if current_user.admin? || pick_var.user_id == current_user.id
          @pick = pick_var
      else
        render nothing: true, status: :forbidden
    end
  end
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/picks/_form.html.erb
<%= simple_form_for(pick_resource, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :pick_team_id, label: false, include_blank: false, collection: [game.team_one, game.team_two], label_method: :name, as: :radio_buttons %>
    <% if current_user.admin? %>
      <%= f.input :wager, label: 'Points', collection: 25..900, :include_blank => false %>
    <% elsif game.bonus == true %>
      <%= f.input :wager, label: 'Points', collection: 25..400, :include_blank => false %>
    <% else %>
      <%= f.input :wager, label: 'Points', collection: 25..300, :include_blank => false %>
    <% end %>
  </div>

  <div class="form-actions">
    <% if game.date < Date.current %>

      <% if current_user.admin? %>
        <%= f.button :submit, class: "btn btn-success" %>
      <% else %>
        <h3>Picks are now closed for this game</h3>
      <% end %>
    <% elsif game.bonus? && game.date <= Date.current %>
      <h3>Picks are now closed for this game</h3>
    <% else %>
      <%= f.button :submit, class: "btn btn-success" %>
      <div id="float-right">
        <h4>Total points wagered this week: <%= @pick.user.weekly_wagers %></h4>
      </div>
    <% end %>
  </div>
<% end %>

app/views/picks/_satsunform.html.erb
<%= simple_form_for(pick_resource, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :pick_team_id, label: false, include_blank: false, collection: [game.team_one, game.team_two], label_method: :name, as: :radio_buttons %>
    <% if current_user.admin? %>
      <%= f.input :wager, label: 'Points', collection: 25..900, :include_blank => false %>
    <% elsif game.bonus == true %>
      <%= f.input :wager, label: 'Points', collection: 25..400, :include_blank => false %>
    <% else %>
      <%= f.input :wager, label: 'Points', collection: 25..300, :include_blank => false %>
    <% end %>
  </div>

  <div class="form-actions">
    <!-- Sunday game -->
    <% if game.date.sunday? %>
      <% if Date.today >= game.date - 1 %>
        <% if current_user.admin? %>
          <%= f.button :submit, class: "btn btn-success" %>
        <% else %>
          <h3>Picks are now closed for this game</h3>
        <% end %>
      <% else %>
        <%= f.button :submit, class: "btn btn-success" %>
        <div id="float-right">
          <h4>Total points wagered this week: <%= @pick.user.weekly_wagers %></h4>
        </div>
      <% end %>
    <!-- Monday game -->
    <% elsif game.date.monday? %>
      <% if Date.today >= game.date - 2 %>
        <% if current_user.admin? %>
          <%= f.button :submit, class: "btn btn-success" %>
        <% else %>
          <h3>Picks are now closed for this game</h3>
        <% end %>
      <% else %>
        <%= f.button :submit, class: "btn btn-success" %>
        <div id="float-right">
          <h4>Total points wagered this week: <%= @pick.user.weekly_wagers %></h4>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/picks/edit.html.erb
<h1>Editing pick</h1>
<% if @game.date.to_time.wday == 4 %>
  <%= render 'form', pick_resource: @pick, game: @game %>
<% else %>
  <%= render 'satsunform', pick_resource: @pick, game: @game %>
<% end %>
<%= link_to 'Back', :back, class: "btn"  %>

app/views/picks/index.html.erb
<h1>Listing Picks for <%= User.find(params[:user_id]).profile_name %></h1>
<hr>
<table class="table-bordered table-striped table-hover">
  <tr>
    <th>Wager</th>
    <th>Pick</th>
    <th>Game Date</th>
    <th>Away Team</th>
    <th>Home Team</th>
  </tr>


<% @picks.each do |pick| %>
  <% if pick.user_id == current_user.id || current_user.admin? %>
    <tr>
      <% if current_user.admin? %>
        <td><%= link_to pick.wager, edit_pick_path(pick) %></td>
      <% else %>
        <td><%= pick.wager %></td>
      <% end %>

      <% if pick.pick_team == Game.find_by(id: pick.game_id).winning_team %>
        <td><strong><%= pick.pick_team.name %></strong></td>
      <% else %>
        <td><%= pick.pick_team.name %></td>
      <% end %>

      <td><%= Game.find_by(id: pick.game_id).date %></td>
      <td><%= Game.find_by(id: pick.game_id).team_two.name %></td>
      <td><%= Game.find_by(id: pick.game_id).team_one.name %></td>
    </tr>

  <% elsif (pick.game.date < Date.current) %>
      <tr>
        <% if current_user.admin? %>
          <% @game = Game.find_by(id: pick.game_id) %>
          <td><%= link_to pick.wager, edit_pick_path(pick) %></td>
        <% else %>
          <td><%= pick.wager %></td>
        <% end %>

        <% if pick.pick_team == Game.find_by(id: pick.game_id).winning_team %>
          <td><strong><%= pick.pick_team.name %></strong></td>
        <% else %>
          <td><%= pick.pick_team.name %></td>
        <% end %>

        <td><%= Game.find_by(id: pick.game_id).date  %></td>
        <td><%= Game.find_by(id: pick.game_id).team_two.name %></td>
        <td><%= Game.find_by(id: pick.game_id).team_one.name %></td>

  <% end %>
<% end %>
<%= paginate @picks %>
</table>

<br />

<%= link_to 'Back', user_leaderboard_path(current_user), class: "btn btn-primary" %>

app/views/picks/new.html.erb
<h1>Make A Pick</h1>
<% if @game.date.to_time.wday == 4 %>
  <%= render 'form', pick_resource: [@game, @pick], game: @game %>
<% else %>
  <%= render 'satsunform', pick_resource: [@game, @pick], game: @game %>
<% end %>

<%= link_to 'Back', games_path %>

app/views/picks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pick team:</b>
  <%= @pick.pick_team.name %>
</p>




<%= link_to 'Edit', edit_pick_path(@pick) %> |
<%= link_to 'Back', picks_path %>