config/routes.rb
Nflpool::Application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations'}

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :games do
    resources :picks, only: [:new, :create]
  end

  resources :users, only: :index do
   resources :picks, only: [:index]
  get "leaderboard"
  end

  resources :picks, only: [:edit, :update]

  root to: 'games#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Replacements</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Graduate">
  <%= favicon_link_tag %>
</head>
<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner main-inner">
				<div class="container">
					<% if current_page? new_user_session_path %>
					<% else %>
						<h3 class="pull-left" id="branded"><%= link_to 'The Replacements', games_path %></h3>
					<% end %>
					<ul class="nav pull-right">

						<% if user_signed_in? %>
							<% if current_user.admin? %>
								<li><%= link_to "Admin", rails_admin_path %></li>
							<% end %>
							<li><%= link_to 'Leaderboard', user_leaderboard_path(current_user.id) %></li>
							<li><%= link_to 'Forum', 'http://replacements.boards.net' %></li>

							<% if current_user.user_points != nil %>
								<li><%= link_to "#{current_user.user_points} Points", user_leaderboard_path(current_user.id) %></li>
							<% else %>
								<li><a href="#">0 Points</a></li>
							<% end%>
							<li><%= link_to current_user.first_name, edit_user_registration_path %></li>
							<li><%= link_to "Log out", logout_path %></li>
						<% else %>
							<li><%= link_to "Log In", login_path %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>


		<% if current_page? new_user_session_path %>
			<header class="hero-unit main-hero">
				<div class="container">
			  		<h1><a href="/">The Replacements</a></h1>
			  		<p>The best way to run your football pool</p>
				</div>
			</header>
		<% end %>
	<div class="container">
		<div class="row">

			<div id="main-content">
				<% flash.each do |type, message| %>
					<div class="alert <%= flash_class type %>">
						<button class="close" data-dismiss="alert">x</button>
							<%= message %>
					</div>
				<% end %>

				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>